apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    k8s-app: elasticsearch
    version: v6.2.5
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      k8s-app: elasticsearch
      version: v6.2.5
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        version: v6.2.5
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: elasticsearch
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-init
        securityContext:
          privileged: true
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/google_containers/elasticsearch:v6.2.5
        name: elasticsearch
        resources:
          limits:
            cpu: 1000m
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 4Gi
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-data
          mountPath: /data
        - name: host-time
          mountPath: /etc/localtime
          readOnly: true
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      storageClassName: ceph-storageclass
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 500Gi
 
