apiVersion: v1
kind: Service
metadata:
  # The name of the elasticsearch service exposed to the outside must be "elasticsearch-logging",
  # because the internal program will find the elasticsearch node from the "elasticsearch-logging" in a hard-coded way
  name: elasticsearch-logging
  namespace: kube-system
  labels:
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
    nodePort: 39200
  selector:
    k8s-app: elasticsearch
