apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: default
spec:
  type: NodePort
  ports:
  - name: web
    port: 8000
    nodePort: 38000
    protocol: TCP
  - name: admin
    port: 8080
    nodePort: 38080
    protocol: TCP
  - name: websecure
    port: 4443
    nodePort: 34443
    protocol: TCP
  selector:
    app: traefik
