apiVersion: v1
kind: Secret
metadata:
  name: traefik-basic-auth
  namespace: default

data:
  # htpasswd -cmb users admin admin
  # htpasswd -mb users passwd passwd
  # cat users | base64
  users: |2
    YWRtaW46JGFwcjEkN0gva3VnN0gkQ0toWnI4aDRwRHVpZzZkS0V5R0dEMApwYXNzd2Q6JGFwcjEk
    Wi8xUEpLMHYkQ3NUTk50Y0dIZ3R2c1RrZkZidkR5MQo=
---

apiVersion: v1
kind: Secret
metadata:
  name: traefik-digest-auth
  namespace: default
data:
  users: |2
    YWRtaW46dHJhZWZpazo4MTczNzQxMTFmMzFjYzI4MjE2MjQ4NjQyNWVlNWU5ZQpwYXNzd2Q6dHJh
    ZWZpazoxMTdiYzkzOTgyMTc2ZWExYjZkNWFiOTNlNTA4MThjNwo=
