apiVersion: v1
kind: Pod
metadata:
  name: busybox-rbd
  #namespace: kube-system
spec:
  restartPolicy: "Never"
  containers:
  - name: busybox
    image: busybox:1.27
    command:
      - "/bin/sh"
      - "-c" 
      - "tail -f /dev/null"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: storage
      mountPath: /mnt
    - name: host-time
      mountPath: /etc/localtime
      readOnly: true
  volumes:
  # this rbd configuration need create rbd image named "busybox-image" use command:
  # ### rbd create --pool kube --image busybox-image --size <size> --image-feature layering
  # then create "ceph-secret-admin" secret in namespace of busybox in kubernetes cluster, use next command:
  # ### ceph auth get-key client.admin > /tmp/key
  # ### kubectl create secret generic ceph-secret-admin --from-file=/tmp/key --type=kubernetes.io/rbd
  - name: storage
    rbd:
      monitors: ["10.71.3.10:6789", "10.71.3.11:6789"] # ceph monitors list
      image: busybox-image
      pool: kube
      user: admin
      #keyring: /etc/ceph/ceph.client.admin.keyring
      secretRef: 
        name: ceph-secret-admin
      fsType: xfs
      readOnly: false
  - name: host-time
    hostPath:
      path: /etc/localtime
    
    
